### ISSUE TITLE
Can't reorder the different layout created

### ISSUE THREAD

**Issue by mikoelsuperbeasto** [reaktivstudios/cmb2-flexible-content#14]
Hello,

Once we created some layout to a page, it would be nice to be able to sort them. The only way seem to delete all of them and re-add all in the order we need?

Look like i got a class 'non-sortable' applied in the markup.. am i missing something?

**Comment by JasonHoffmann** [comment]
Hmm, I would need to take a look but you may have some luck by adding the sortable option to the registered field, so it would be:
```
$cmb->add_field( array(
	'name'       => __( 'Test Flexible', 'cmb2-flexible' ),
	'desc'       => __( 'field description (optional)', 'cmb2-flexible' ),
	'id'         => 'prefix_flexible',
	'type'       => 'flexible',
        'options'   => array( 'sortable' => true ),
	'layouts' => ...
) );
```

In theory this should support anything that [CMB2 groups](https://github.com/CMB2/CMB2/wiki/Field-Types#group) support, but this plugin is still in beta right now, and we need to do further testing and some fixes.

**Comment by mikoelsuperbeasto** [comment]
Look like it will need some fixes, i still can't get sortable working

` $blocs_config = new_cmb2_box( array(
            'id'            => $prefix . 'blocs_config',
            'title'         => __( 'Mise en page' ),
            'object_types'  => array( 'page' ) // Post type
        ) );

        $blocs_config->add_field( array(
            'name'       => __( 'Blocks'),
            'id'         => $prefix . 'blocks',
            'type'       => 'flexible',
            'options'   => array( 'sortable' => true ),
            'layouts' => array(
                'text' => array(
                    'title' => ...`

**Comment by mikoelsuperbeasto** [comment]
Part of the issue must be in the function called create_group(). The variable $group_args is not getting the options defined.

```
 $group_args = array(
    'id' => $field_id,
    'type' => 'group',
    'context' => 'normal',
    'repeatable' => true,
    'show_names' => true,
    'classes' => array( 'cmb-flexible-wrap' ),
    'fields' => array(),
     'options' => array(),
);

    $field = $field->get_field_clone( $group_args );
```

**Comment by mikoelsuperbeasto** [comment]
i'm kind of new to CMB2 (coming from ACF) and i was searching for a drag n' drop feature... i just saw the arrow making sortable great! Wow.. sorry!
